- package-lock.json
- package.json
Adiciona o jest como dependência de desenvolvimento para rodar os testes automatizados
> chore(jest): adiciona o test runner Jest

- .prettierignore
- package-lock.json
- package.json
Adiciona o prettier e scripts relacionados para permitir formatação padronizada do códgio.
> chore(prettier): adicionar o prettier

- .editorconfig
- .eslintrc
- next.config.js
- package-lock.json
- package.json
adiciona o eslint e scripts relacionados
> chore(eslint): adiciona o eslint

- jest.config.js
configura o jest com o next para facilitar configurações e permitir compatibilidade com ESModules
> chore(jest): configura o jest com next

- .github/workflows/ci.yml
Adiciona yml do github actions para configurar o CI
> chore(ci): adiciona ci

- .github/workflows/ci.yml
corrige erro no lint:check do arquivo de configuração do ci
> fix(ci): corrige erro no ci

- .github/workflows/ci.yml
- src/app/route.js
adiciona uma rota hello world da api
> feat(hello-world): adiciona primeira rota da api

- .env
- .github/workflows/ci.yml
- .sequelizerc
- docker-compose.development.yml
- infra/database/config.js
- infra/database/connection.js
- package-lock.json
- package.json
- src/app/route.js
adiciona instância de banco de dados de desenvolvimento, configura migrations e configura conexões 
através das variáveis de ambiente
> chore(database): adiciona sequelize e docker

- src/app/page.js
- src/app/route.js
adiciona página em construção e xclui rota inicial
> feat(home): adiciona página "em contrução..."

- infra/webserver.js
adiciona webserver na infra para obter host e ambiente atual
> feat(webserver): adiciona webserver para identificar host

- utils/date-booster.js
Adiciona `utils` com `date-booster` para adicionar métodos personalizados ao objeto nativo `Date`. Inicialmente adiciona o método para obter uma datetime string no formato de input do banco de dados.
> chore(date): adiciona date-booster

- src/app/status/route.js
implementa rota `status` que verifica conexões com banco de dados
> feat(status): implementa rota status

- utils/errors.js
adiciona classes de erro para melhor tratamento de erros e melhor provisionamento de mensagens para o user final
> feat(errors): adiciona novas classes de erro

- src/app/v1/auth-service/email-verification/POST.test.js
- src/app/v1/auth-service/email-verification/route.js
- src/app/v1/selection-service/current-selection/route.js
- utils/controller.js
- utils/errors.js
adiciona os controlers, adapta respostas dos endpoints já implementados e corrige tratamento de erro
BREAKING CHANGE: novas respostas de errors para os endpoints existentes
> feat(controller): adicionar controller para manipulação de respostas

- infra/migrations/1700045151789_create-selections-tables.js
- src/models/selection.js
- utils/tests-orchestration/selection-orchestrator.js
muda o nome de `selection_steps` para `selections_steps`para deixar maior coerência de nomenclatura do código
> refactor(selections): muda o nome da tabela selections_steps

- src/app/v1/orders-service/webhook_mp/payments/POST.test.js
- src/app/v1/orders-service/webhook_mp/payments/route.js
- src/models/order.js
- src/services/orders/payment-processor.js
o webhook será responsável por receber atualizações sobre pagamentos vindas do mercado pago
> feat(webhook): implementa endpoint de entrada para webhook mercado pago

- infra/migrations/1700538404550_create-orders-tables.js
- package-lock.json
- package.json
- src/app/v1/orders-service/orders/[id]/payments/POST.test.js
- src/app/v1/orders-service/webhook_mp/payments/route.js
- src/app/v1/selection-service/applications/[id]/orders/GET.test.js
- src/models/application.js
- src/models/order.js
- src/services/orders/orders-control.js
- src/services/orders/payment-methods.js
- src/services/orders/payment-processor.js
- utils/controller.js
- utils/tests-orchestration/orders-orchestration.js
adiciona um status que é calculado a cada query, considerando o status de todos os pagamentos presentes
> feat(orders): adiciona status dinâmico para orders

- src/app/v1/auth-service/token/POST.test.js
- src/app/v1/auth-service/token/[token]/GET.test.js
- src/app/v1/auth-service/token/[token]/route.js
- src/services/auth/email-verification.js
- src/services/auth/token-generator.js
- utils/tests-orchestration/auth-orchestrator.js
remove role dos tokens gerados por `email_verification` e altera o código HTTP de erro para tokens
incorretos na tentativa de geração de novo token por `email_verification`
adiciona rota para verificação de tokens
> feat(token): corrige token e adiciona rota para verificação de token

- package.json
- utils/controller.js
- utils/errors.js
fix(errors): adiciona errorid e corrige logging de errors
build(migrations): adiciona migrations ao build
> build(): mudanças no build

- src/app/v1/auth-service/email-verification/POST.test.js
- src/app/v1/auth-service/email-verification/route.js
adiciona validação e suas respectivas mensagens de erro para melhorar a informação de erro para o usuário
> feat(email): adiciona validação de email na verificação de email

- src/app/v1/selection-service/applications/route.js
- src/services/selection/applications-form.js
corrige problemas como data de expiração da `order` da inscrição, campos com valores null e problemas com amount no pagamento
> fix(applications): corrige problemas na inscrição

- infra/migrations/1700538404550_create-orders-tables.js
- src/app/v1/selection-service/applications/[id]/orders/GET.test.js
- src/models/application.js
- src/models/order.js
- src/models/socioeconomic.js
- src/services/orders/orders-control.js
- src/services/orders/payment-processor.js
- src/services/selection/applications-form.js
- src/services/selection/socioeconomic-form.js
- utils/tests-orchestration/selection-orchestrator.js
- Remove o NOT NULL para `payer_email` e altera `mercado_pago_id` para bigint
- Corrigir queries para `status` das `orders`
- Adicionar item para pagamento na api do mercado pago (com title do order)
- Corrige `countApplicationAnswersByQuestionId` para verificação de respostas duplicadas
> fix(payments): corrige diversos erros do sistema de pagamentos

- src/services/selection/socioeconomic-form.js
> perf(socioeconomic): tenta melhorar tempo de resposta do form socioeconomico

- src/app/v1/selection-service/socioeconomic/answers/POST.test.js
- src/services/selection/socioeconomic-form.js
remove a liberação temporária para questionário socioeconômico
> revert(socioeconomic): remove liberação temporária de edição socio
